# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,QtWebEngineWidgets
import pathlib

CSV_PATH = ""

class Ui_MainWindow(object):
    def on_click(self):
        self.label.setText(CSV_PATH)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.load(QtCore.QUrl().fromLocalFile(str(pathlib.Path(pathlib.Path(__file__).parent.resolve()) / r"nx.html")))
        self.verticalLayout.addWidget(self.webEngineView,70)

        self.main_tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.tab_layout = QtWidgets.QWidget()
        self.tab_layout.setObjectName("tab_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_layout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_layout_vertical_left = QtWidgets.QVBoxLayout()


        self.tab_layout_vertical_left.setObjectName("tab_layout_vertical_left")
        self.pushButton = QtWidgets.QPushButton(self.tab_layout)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.on_click)


        self.tab_layout_vertical_left.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.tab_layout_vertical_left)
        self.tab_layout_vertical_right = QtWidgets.QVBoxLayout()
        self.tab_layout_vertical_right.setObjectName("tab_layout_vertical_right")
        self.label = QtWidgets.QLabel(self.tab_layout)
        self.label.setObjectName("label")
        self.tab_layout_vertical_right.addWidget(self.label)
        self.horizontalLayout.addLayout(self.tab_layout_vertical_right)
        self.main_tab_widget.addTab(self.tab_layout, "")
        self.tab_attribute = QtWidgets.QWidget()
        self.tab_attribute.setObjectName("tab_attribute")
        self.main_tab_widget.addTab(self.tab_attribute, "")
        self.tab_node_edge = QtWidgets.QWidget()
        self.tab_node_edge.setObjectName("tab_node_edge")
        self.main_tab_widget.addTab(self.tab_node_edge, "")
        self.verticalLayout.addWidget(self.main_tab_widget, 30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Excel file name"))
        self.label.setText(_translate("MainWindow", "Click to show"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_layout), _translate("MainWindow", "Layout"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_attribute), _translate("MainWindow", "Attribute"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_node_edge), _translate("MainWindow", "Node / Edge"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
